"""init

Revision ID: 251e67657130
Revises: 
Create Date: 2024-01-16 23:35:25.834319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251e67657130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=32), nullable=False),
    sa.Column('mbti', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('job', sa.String(length=32), nullable=False),
    sa.Column('profile_image', sa.String(length=256), nullable=True),
    sa.Column('original_images', sa.JSON(), nullable=True),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('booth_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synopses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('genre', sa.String(length=32), nullable=False),
    sa.Column('background', sa.String(length=32), nullable=False),
    sa.Column('ending', sa.String(length=32), nullable=False),
    sa.Column('event_description', sa.TEXT(), nullable=False),
    sa.Column('contents', sa.JSON(), nullable=True),
    sa.Column('conversation', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synopses_characters',
    sa.Column('synopsis_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['synopsis_id'], ['synopses.id'], ),
    sa.PrimaryKeyConstraint('synopsis_id', 'persona_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synopses_characters')
    op.drop_table('synopses')
    op.drop_table('personas')
    # ### end Alembic commands ###
