"""add prompt

Revision ID: 6a12265e8844
Revises: 251e67657130
Create Date: 2024-01-16 23:37:31.418353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a12265e8844'
down_revision: Union[str, None] = '251e67657130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job', sa.TEXT(), nullable=False),
    sa.Column('male_prompt', sa.TEXT(), nullable=False),
    sa.Column('female_prompt', sa.TEXT(), nullable=False),
    sa.Column('negative_prompt', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    # ### end Alembic commands ###
